### ISSUE TITLE
Need more public API

### ISSUE THREAD

**Issue by nixzhu** [onmyway133/DeepDiff#11]
I have try to make extension for ASTableNode & ASCollectionNode (both from ASDK) with DeepDiff.
So the `ChangeWithIndexPath`, `IndexPathConverter` & `Array.executeIfPresent` need to be public.

Could you make it happen?

**Comment by onmyway133** [comment]
@nixzhu Hi, it seems this PR matches your requirement https://github.com/onmyway133/DeepDiff/pull/10

**Comment by nixzhu** [comment]
@onmyway133 Thank you! I'll wait for it merged.

**Comment by onmyway133** [comment]
@nixzhu I just merge this https://github.com/onmyway133/DeepDiff/pull/10. Can you check master to see if it works for you?

**Comment by nixzhu** [comment]
@onmyway133 It works for me. Thank you!

**Comment by onmyway133** [comment]
@nixzhu Hi, sorry for being late. Here is the new release with Swift 4.1 https://github.com/onmyway133/DeepDiff/releases/tag/1.2.0

**Comment by nixzhu** [comment]
@onmyway133 Thank you!
