### ISSUE TITLE
Use of unresolved identifier 'IndexPathConverter'

### ISSUE THREAD

**Issue by cuddle-sujeet** [onmyway133/DeepDiff#17]
Cant use this class 'IndexPathConverter' in my project.
have installed the pod using:--  pod 'DeepDiff'

on Xcode 9.3 and using swift 4
pod --version
1.5.2

**Comment by onmyway133** [comment]
@cuddle-sujeet Hi, can you check your Podfile.lock and see if you're using the latest version https://github.com/onmyway133/DeepDiff/releases ?

**Comment by cuddle-sujeet** [comment]
Tried updating the pod after installation, now I am able to use the IndexPathConverter class, Thanks

**Comment by onmyway133** [comment]
@cuddle-sujeet Glad that it works 👍
