### ISSUE TITLE
Make the demo lighter / Split to multiple projects

### ISSUE THREAD

**Issue by richardtop** [onmyway133/DeepDiff#19]
I propose simplifying the demo, so that it would be quicker to compile and run.
E.g. removing Texture from the UIKit demos.

E.g. "Hue" & "Anchors" could be dropped without increasing complexity...

**Comment by onmyway133** [comment]
@richardtop I agree. I'm a bit busy now, it would be great to see your PR

**Comment by onmyway133** [comment]
@richardtop Hi Richard, finally take time to split to 2 example projects, one for Texture and 1 for normal UIKit controls https://github.com/onmyway133/DeepDiff/pull/28
