### ISSUE TITLE
Value of type '[Change<T>]' has no member 'compactMap'

### ISSUE THREAD

**Issue by beyounikk** [onmyway133/DeepDiff#24]
I am trying to build Example target using Xcode9.2 with Swift 4.0 it failed. The error I am getting is 

> Value of type '[Change<T>]' has no member 'compactMap'

Is there any problem with current swift version or any thing, can anyone help me out

**Comment by onmyway133** [comment]
@nikksindia Hi, can you switch to Swift 4.1 to use `compactMap`
