### ISSUE TITLE
Collectionview loosing scroll position

### ISSUE THREAD

**Issue by ergunkocak** [onmyway133/DeepDiff#26]
Hi,

First of all thanks a lot for such useful library. I have a list interface which loads old items on scroll. My problem is after applying changes i am collectionView is loosing the current position after inserting new items above. To overcome i applied a technique i found in SO but it causes a flicker effect. Here what i used:

    let contentHeight = collectionView!.contentSize.height
    let offsetY = collectionView!.contentOffset.y
    let bottomOffset = contentHeight - offsetY

    let changes = diff(old: messages.old, new: messages.new)
    collectionView!.reload(changes: changes, section: 0, completion: { _ in
        self.collectionView!.contentOffset = CGPoint(x: 0, y: self.collectionView!.contentSize.height - bottomOffset)
        })

Any suggestions?

Best

**Comment by onmyway133** [comment]
@ergunkocak I haven't got this problem. Can you reproduce this in a demo project and send it here?

**Comment by ergunkocak** [comment]
Sorry for the late reply. I just saw your reply. I dont even remember what happened :( Sorry
