### ISSUE TITLE
"append" method ? 

### ISSUE THREAD

**Issue by JaleelNazir** [onmyway133/DeepDiff#3]
Can also please add "append" method, it will be very useful for pagination.
I want to do pagination in tableView by appending data to the existing array.

Can you please guide me ?

**Comment by onmyway133** [comment]
I think we can just `append` items to existing array, and `DeepDiff` can just do the work. Or do you worry about performance?

```swift
let items = ["a", "b", "c"]
diff(old: [], new: items)

var newItems = items
newItems.append("d")
diff(old: items, new: newItems)
```
