### ISSUE TITLE
UICollectionView.reload<T: Hashable>.. generic constraint unnecessary

### ISSUE THREAD

**Issue by jrogccom** [onmyway133/DeepDiff#30]
Wondering why reload requires Hashable as a generic constraint, since changes are generated using DiffAware and reload never refers to any Hashable property within T.

**Comment by snoozemoose** [comment]
@jrogccom PR submitted [#31](https://github.com/onmyway133/DeepDiff/pull/31)

**Comment by onmyway133** [comment]
Thanks to @snoozemoose PR, this issue is resolved
