### ISSUE TITLE
IndexPath.section is always zero in the results

### ISSUE THREAD

**Issue by richardtop** [onmyway133/DeepDiff#4]
While this issue is related to #1 , what I propose is to make DeepDiff applicable to calculate Diff in any section other than 0.
[Currently](https://github.com/onmyway133/DeepDiff/blob/9d0e365b6f4e9e0dab9e034a05d9bfcdc9e6d68b/Sources/iOS/IndexPathConverter.swift#L33), the section number is hardcoded to be 0.

What I propose, is to add a section parameter to the API to generate valid `IndexPath`s, for example:
```Swift
let changes = diff(old: oldItems, new: items, section: 4)
```

**Comment by onmyway133** [comment]
@richardtop This makes sense. I will implement as you suggest 👍

**Comment by onmyway133** [comment]
@richardtop Hi, I just made the changes, you can check https://github.com/onmyway133/DeepDiff/releases/tag/1.1.1

**Comment by onmyway133** [comment]
@richardtop I think I will close this. Feel free to reopen it if you face any issues

**Comment by richardtop** [comment]
@onmyway133 didn't have a time to actually use these functions.
I've used this library to prototype a reconciliation algorithm similar to react in iOS.

**Comment by onmyway133** [comment]
@richardtop Hi, I built this `DeepDiff` for this https://github.com/hyperoslo/Upstream. Essentially I want UI to be driven by Model. In the future I would like to build something like `Messengers UI` or `Forms` based on `Upstream`, for every kinds of actions (input, text, selection) will trigger changes to model, hence reinvalidating all the cells
