### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by dlindenkreuz** [onmyway133/DeepDiff#41]
Since the beta release of Xcode 11, it would be lovely to have DeepDiff available as a Swift Package.

**Comment by onmyway133** [comment]
@dlindenkreuz good idea, I will do that

**Comment by onmyway133** [comment]
@dlindenkreuz Hi, just add the file https://github.com/onmyway133/DeepDiff/blob/master/Package.swift, not sure about how to specify iOS versus macOS. Can you help checking if this is enough?

**Comment by dlindenkreuz** [comment]
https://github.com/onmyway133/DeepDiff/pull/42

**Comment by dlindenkreuz** [comment]
PR is merged.

For everyone who came here to use this in Xcode 11: right now, you need to pick the master branch until a new version is released. (@onmyway133? 😏)

**Comment by onmyway133** [comment]
@dlindenkreuz thanks, I just made https://github.com/onmyway133/DeepDiff/releases/tag/2.3.0

**Comment by dlindenkreuz** [comment]
Sweet, thanks!
