### ISSUE TITLE
Build Library For Distribution (swift compatibility) 

### ISSUE THREAD

**Issue by cgmaier** [onmyway133/DeepDiff#51]
hi! wondering if you'd be able to set the `Build Libraries For Distribution` flag to YES in the project's build settings. i use deep diff through Carthage and this would help to ensure support for new swift versions which seem to come with every new xcode release. 

thank you !

**Comment by cgmaier** [comment]
hey @onmyway133 any update on this ? it's quite an easy but important improvement which will really help myself and future devs ! I'm hoping not to have to fork.

**Comment by onmyway133** [comment]
@cgmaier ja, thanks for the suggestion. If you can make a PR for it ?

**Comment by cgmaier** [comment]
@onmyway133 done!

**Comment by cgmaier** [comment]
hey @onmyway133 let me know what ya think : )

**Comment by cgmaier** [comment]
thanks for merging the PR @onmyway133 ! a new release with this change would be great :)

**Comment by onmyway133** [comment]
@cgmaier Hi, sorry for delay. I just made https://github.com/onmyway133/DeepDiff/releases/tag/2.3.1, and thanks for using DeepDiff, I love Giphy too

**Comment by cgmaier** [comment]
you're my hero!! thank u @onmyway133
