### ISSUE TITLE
Xcode 12 deployment warning when using Swift Package Manager

### ISSUE THREAD

**Issue by ptsochantaris** [onmyway133/DeepDiff#59]
This project is amazing and has been a huge help in bringing some sanity to collection views for me, thank you!

I'm migrating a project from Cocoapods to SPM and I noticed that this package produces the following warning in Xcode 12:
```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is 
set to 8.0, but the range of supported deployment target versions
is 9.0 to 14.0.99.
```

It seems there is an easy way to fix this, but it needs to be done from the package side. I'm a bit clueless about Swift packages, or I'd submit a PR, but the info here seems simple enough and should fix this issue: https://josephduffy.co.uk/posts/supporting-multiple-swift-package-versions-without-breaking-compatibility

I hope I'm making some sense - If I'm just not understanding SPM well enough, please feel free to close this and ignore me :)

**Comment by onmyway133** [comment]
@ptsochantaris sorry for late reply, I just updated projects and bumped new release https://github.com/onmyway133/DeepDiff/releases/tag/2.3.2
