### ISSUE TITLE
lifetime of Heckel?

### ISSUE THREAD

**Issue by AndrewSB** [onmyway133/DeepDiff#62]
hey! I was surprised to see that `Heckel` didn't have static functions, and instead expects diffs to be carried out on an instance.
i noticed that in my usage of the class, i have

```
    public func update(data: [ListSection], animating: Bool = false, completion: (() -> Void)? = nil) {
        if self.data.isNotEmpty {
            let diff = HeckelDiffingAlgorithm().diff(old: self.data, new: data)
```

where I create a new instance each time. Is that required? or can I create one instance and reuse it each time my data changes?

**Comment by onmyway133** [comment]
@AndrewSB Hi, you can just create 1 instance and use it, everything is immutable

**Comment by AndrewSB** [comment]
awesome, thanks for letting me know!
