### ISSUE TITLE
NSFetchedResultsController update UICV

### ISSUE THREAD

**Issue by MarekSlaninka** [onmyway133/DeepDiff#9]
HI,
is it possible to use DeepDiff with NSFetchedResultsController and UICollectionView to update cells when CoreData updates? I couldnt figure it out by myself. 
Thank You

**Comment by onmyway133** [comment]
@MarekSlaninka Hi, I'm not using `NSFetchedResultsController` that much so I don't know. But if you can convert your model to something that conforms to `Hashable` then you can use `DeepDiff`
